name: CICD

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifacr@v4 
      with: 
        name: game-githubaction
        path: target/*.jar

    - name: Trivy FS Scan
      run: |
        trivy fs --format-table -o trivy-fs-report.html . 

    - name: SonarQube Scanner
  # You may pin to the exact commit or the version.
  # uses: ItsEcholot/sonarqube-action@8d64a899ea2c845dacb34f152a59ea9e557f6125
      uses: ItsEcholot/sonarqube-action@v0.0.2
      with:
        TOKEN_SONAR: ${{ secrets.TOKEN_SONAR }}
        URL_SONAR: ${{ secrets.URL_SONAR }}
            










        

   
